export const dataInputBlog = [
    {
        id: "1",
        label: "Тэги",
        name: "tags",
        required: true,
        minLength: 2,
        messages: "textName",
        placeholder: "Тэги",
        isGroup: true,
    },
    {   
        id: "2",
        label: "Название",
        name: "title",
        required: true,
        minLength: 2,
        messages: "textName",
        placeholder: "Название",
    },
    {
        id: "3",
        label: "Краткое описание",
        name: "short_description",
        required: true,
        minLength: 30,
        messages: "textareaLength",
        placeholder: "Краткое описание",
    },
    {
        id: "4",
        label: "Автор",
        name: "author",
        required: true,
        minLength: 2,
        messages: "textName",
        placeholder: "Автор",
    },
    {
        id: "5",
        label: "Также прочитать",
        name: "alsoRead",
        required: true,
        fields: [
            {
                id: "5.1",
                label: "Id товара",
                name: "url",
                required: true,
                value: "idRegex",
                messages: "validURL",
                placeholder: "Введите id товара",
            },
            {
                id: "7.1",
                label: "Заголовок",
                name: "title",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Введите подзаголовок",
            },
        ],
    },
    {
        id: "6",
        label: "Описание",
        name: "description",
        required: true,
        minLength: 130,
        fields: [
            {
                id: "6.1",
                label: "Подзаголовок",
                name: "subTitle",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Введите подзаголовок",
            },
            {
                id: "6.2",
                label: "Абзацы",
                name: "paragraphs",
                required: true,
                minLength: 30,
                messages: "textareaLength",
                placeholder: "Введите абзацы",
            },
        ],
        isGroup: true,
    },
    {
        id: "7",
        label: "Списки",
        name: "list",
        required: false,
        minLength: 10,
        fields: [
            {
                id: "7.1",
                label: "Подзаголовок",
                name: "subTitle",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Введите подзаголовок",
            },
            {
                id: "7.2",
                label: "Пункты",
                name: "points",
                required: true,
                minLength: 10,
                messages: "textareaLength_list",
                placeholder: "Введите абзацы",
            },
        ],
        isGroup: true,
    },
    {
        id: "8",
        label: "Фильтры",
        name: "filter",
        required: true,
        minLength: 2,
        messages: "textName",
        placeholder: "Фильтры",
        isGroup: true,
    },
    {
        id: "9",
        label: "Контент",
        name: "content",
        required: true,
        minLength: 2,
        messages: "textName",
        placeholder: "Контент",
        isGroup: true,
    }
]

