export const dataInputProduct = [
    {
        id: "1",
        label: "Категории",
        name: "categories",
        required: true,
        fields: [
            {
                id: "1.1",
                label: "Обозначение",
                name: "value",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Введите название",
            },
            {
                id: "1.2",
                label: "Значение",
                name: "label",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Введите значение",
            },
        ],
        isGroup: true,
    },
    {
        id: "2",
        label: "Название",
        name: "name",
        required: true,
        minLength: 2,
        messages: "textName",
        placeholder: "Название",
    },
    {
        id: "3",
        label: "Краткое описание",
        name: "short_description",
        required: true,
        minLength: 30,
        messages: "textareaLength",
        placeholder: "Краткое описание",
    },
    {
        id: "4",
        label: "Цена",
        name: "price",
        required: true,
        value: 'numberRegex',
        messages: "validNumbers",
        placeholder: "Укажите цену",
    },
    {
        id: "5",
        label: "Скидочная цена",
        name: "sale_price",
        required: true,
        value: 'numberRegex',
        messages: "validNumbers",
        placeholder: "Скидочная цена",
    },
    {
        id: "6",
        label: "Наличие",
        name: "availability",
        required: true,
        fields: [
            {
                id: "6.1",
                label: "Обозначение",
                name: "value",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Введите название",
            },
            {
                id: "6.2",
                label: "Значение",
                name: "label",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Введите значение",
            },
        ],
    },
    {
        id: "7",
        label: "Теги",
        name: "tags",
        required: true,
        minLength: 2,
        messages: "textName",
        placeholder: "Теги",
        isGroup: true,
    },
    {
        id: "8",
        label: "Артикул",
        name: "article_number",
        required: true,
        value: 'numberRegex',
        messages: "validNumbers",
        placeholder: "Артикул",
    },
    {
        id: "9",
        label: "Описание",
        name: "description",
        required: true,
        fields: [
            {
                id: "9.1",
                label: "Параграфы",
                name: "paragraphs",
                required: true,
                minLength: 30,
                messages: "textName",
                placeholder: "Параграфы",
                isGroup: true,
            },
            {
                id: "9.2",
                label: "Пункты",
                name: "list",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Пункты",
                isGroup: true,
            },
        ],
    },
    {
        id: "10",
        label: "Информация",
        name: "information",
        required: true,
        fields: [
            {
                id: "10.1",
                label: "Материал",
                name: "material",
                required: true,
                fields: [
                    {
                        id: "10.1.1",
                        label: "Обозначение",
                        name: "value",
                        required: true,
                        minLength: 2,
                        messages: "textName",
                        placeholder: "Введите название",
                    },
                    {
                        id: "10.1.2",
                        label: "Значение",
                        name: "label",
                        required: true,
                        minLength: 2,
                        messages: "textName",
                        placeholder: "Введите значение",
                    },
                ],
                isGroup: true,
            },
            {
                id: "10.2",
                label: "Цвета",
                name: "color",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Цвета",
                isGroup: true,
            },
            {
                id: "10.3",
                label: "Масса",
                name: "weight",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Масса",
            },
            {
                id: "10.4",
                label: "Размеры",
                name: "dimensions",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Размеры",
            },
            {
                id: "10.5",
                label: "Бренд",
                name: "brand",
                required: true,
                minLength: 2,
                messages: "textName",
                placeholder: "Бренд",
            },
        ],
    }
]



